name: Auto refresh Airtable metadata

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run refresh:airtable
        env:
          AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_CONTACTS_TABLE_NAME: ${{ secrets.AIRTABLE_CONTACTS_TABLE_NAME }}
          AIRTABLE_LOGS_TABLE_NAME: ${{ secrets.AIRTABLE_LOGS_TABLE_NAME }}
          AIRTABLE_SNAPSHOTS_TABLE_NAME: ${{ secrets.AIRTABLE_SNAPSHOTS_TABLE_NAME }}
          AIRTABLE_THREADS_TABLE_NAME: ${{ secrets.AIRTABLE_THREADS_TABLE_NAME }}
      - name: Commit and push changes
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@users.noreply.github.com'
          if ! git diff --quiet; then
            git add api/resolveFieldMap.ts custom_action_schema.json
            git commit -m 'chore: auto-refresh Airtable metadata'
            git push
          fi
